<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\TableCsv\TableCsv\TableCsv.csproj" />
    <ProjectReference Include="..\Table\Table\Table.csproj" />
  </ItemGroup>

</Project>
